app/models.py
from . import db, login_manager
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    password_hash = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pitch = db.relationship('Pitch', backref='pitch_user', lazy="dynamic")
    Comments = db.relationship('Comment', backref='user', lazy="dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'User {self.username}'

    @login_manager.user_loader
    def load_user(users_id):
        return User.query.get(int(users_id))


class Pitch(db.Model):
    __tablename__ = 'pitch'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), index=True)
    pitch = db.Column(db.String(300), index=True)
    type = db.Column(db.String(255))
    time = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref='pitch_comment', lazy="dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitch(cls, id):
        pitch = Pitch.query.filter_by(type_id=id).all()
        return pitch

    @classmethod
    def get_pitch_user(cls, id):
        pitch = Pitch.query.filter_by(user_id=id).all()
        return pitch


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment_post = db.Column(db.String(255), index=True)
    time = db.Column(db.DateTime, default=datetime.utcnow)
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitch.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def save_comments(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, id):
        comments = Comment.query.filter_by(pitch_id=id).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, RadioField
from wtforms.validators import DataRequired


class PitchForm(FlaskForm):
    title = StringField(' Title', validators=[DataRequired()])
    pitch = TextAreaField('Your Pitch', validators=[DataRequired()])
    type = RadioField('Type', choices=[('interview', 'interview_pitch'),('promotion', 'promotion_pitch')])
    submit = SubmitField('Submit')


class CommentsForm(FlaskForm):
    comment = TextAreaField('Comments', validators=[DataRequired()])
    submit = SubmitField('Submit')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
from config import Config_options
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads,IMAGES
from flask_bootstrap import Bootstrap

db = SQLAlchemy()
mail = Mail()
bootstrap = Bootstrap()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos', IMAGES)


def create_app(config_name):
    app = Flask(__name__)

    # app configuration

    app.config.from_object(Config_options[config_name])

    # register blueprint
    from .main import main  as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    # Initializing Flask Extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # configure UploadSet
    configure_uploads(app, photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views, error

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from flask_login import login_required, current_user
from ..models import Pitch, Comment, User
from .forms import PitchForm, CommentsForm, UpdateProfile
from .. import db, photos


@main.route('/')
def index():
    """
    View root page function that returns the index page and its data
    """
    return render_template('index.html')


@main.route('/category/interview', methods=["GET", "POST"])
def interview():
    '''
    A view function that will return the pitches on a specific kind of view
    '''

    types = Pitch.query.filter_by(type='interview').all()
    # title = f'{types} pitch'

    return render_template('interview.html', types=types)


@main.route('/category/promotion', methods=["GET", "POST"])
def promotion():
    '''
    A view function that will return the pitches on a specific kind of view
    '''

    types = Pitch.query.filter_by(type='promotion').all()
    title = f'{types} pitch'

    return render_template('promotion.html', title=title, types=types)


@main.route('/category/add_pitch', methods=["GET", "POST"])
@login_required
def add_pitch():
    '''
    view function that helps renders theform to create a new pitch
    '''

    pitch_form = PitchForm()

    if pitch_form.validate_on_submit():
        pitch = pitch_form.pitch.data
        title = pitch_form.title.data
        type = pitch_form.type.data

        new_pitch = Pitch(title=title, pitch=pitch, type=type)
        new_pitch.save_pitch()
        return redirect(url_for('.index'))

    title = 'ADD PITCH'
    return render_template('add_pitch.html', title=title, pitch_form=pitch_form)


@main.route('/comments/new/<int:id>', methods=["GET", "POST"])
@login_required
def comment(id):
    """
    view function that return a form to comment on a given pitch
    """

    form = CommentsForm()
    pitch = Pitch.query.filter_by(id=id).first()
    if form.validate_on_submit():
        comment = form.comment.data
        new_comment = Comment(comment_post=comment, user=current_user)
        new_comment.save_comments()

        return redirect(url_for('.comments', id=pitch.id))
    title = f'{pitch.title} comments'
    return render_template('new_comment.html', title=title, comment_form=form, pitch=pitch)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username=uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user, types=types)


@main.route('/user/<uname>/update', methods=['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname=user.username))

    return render_template('profile/update.html', form=form)


@main.route('/user/<uname>/update/pic', methods=['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username=uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname))

app/templates/add_pitch.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
                {{ wtf.quick_form(pitch_form) }}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block styles %}
    {{super()}}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Dosis&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">

{% endblock %} 

app/templates/comments.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container">
    <div class="legend">
      
        <h3 class="text-center">Comment Logs</h3>
        <hr>
        {% if comment %}
        <div class="row">
            {{ macro.displayComments(comment) }}
        </div>
        {% else %}
        <h3>No comments yet</h3>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}

{% block content %}

<div class="container">
        <h1 class="text-header text-center">{{title}}</h1>

    <div class="row">
        <a href="{{url_for('main.add_pitch')}}">Submit</a>
        <a href="{{url_for('main.interview')}}">Interview</a>
        <a href="{{url_for('main.promotion')}}">Promotion</a>

    </div>
</div>

{% endblock %}

app/templates/interview.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {{macro.displayTypes(types)}}
        </div>
        <div class="col md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/macros.html
{% macro displayTypes(my_list) %}
{%  for type in my_list %}
<div class="col-sm-3">
    <div class="card m-1" style="width: 15rem;">

        <div class="card-body">
            <h5 class="card-title">{{type.title}}</h5>
            <p class="card-text">Take a minute of your life to do something awesome to change the world ,it really feels
                good.</p>
            <a href="/category/{{type.id}}" class="btn btn-info">view pitches</a>
        </div>
    </div>
</div>
{% endfor %}
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Pitches</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/" title="home" ><i class="fas fa-home"></i><span class="sr-only">(current)</span></a>
            <a class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/category/1">Sales Pitches</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="/category/2">Interview Pitches</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="/category/3">Personal Pitches</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="/category/4">PickUplines Pitches</a>

                    </div>
                </a>
        </div>


        <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{url_for('main.profile',uname=current_user.username)}}" title="profile"><i class="fas fa-user"></i> {{current_user.username}}</a>
                <a class="nav-item nav-link" href="{{url_for('auth.logout')}}">Sign out <i class="fas fa-sign-out-alt"></i> </a>
                {% else %}
                <a class="nav-item nav-link" href="{{url_for('auth.login')}}">Sign in</a>
                {%endif%}category/add_pitch

        </div>
    </div>
</nav>

app/templates/new_comment.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {{ wtf.quick_form(comment_form) }}
        </div>
        <div class="col md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}

{% block content %}

<div class="container">

    <div class="row">
       {{macro.Pitch(pitch)}}
    </div>
</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
   <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/promotion.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {{macro.displayTypes(types)}}
        </div>
        <div class="col md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/type.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block content%}
<h5 class="text-center">{{types.name}}</h5>
<hr>
<a class="btn btn-sm btn-outline-info center ml-5 m-2 btn-float" href="/category/add_pitch/{{cat_id}}" style="position: relative;">Add pitch</a>

<div class="container">
   <div class="row">
       {% if pitch %}

       {{macro.displayPitch(pitch)}}
       {% else %}
         <h4 class="text-center"> No pitches yet</h4>
         
        {% endif %}
   </div> 
</div>

{% endblock %}